# Generated by Django 2.0.5 on 2018-05-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyous', '0004_auto_20180425_2355'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsindexpage',
            name='page_ptr',
        ),
        migrations.CreateModel(
            name='CalendarPage',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name': 'Calendar',
            },
            bases=('joyous.calendarpage',),
        ),
        migrations.DeleteModel(
            name='EventsIndexPage',
        ),
    ]
